apiVersion: v1
kind: Secret
metadata:
  name: nekocafe-secrets
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/part-of: nekocafe
type: Opaque
stringData:
  DB_PASSWORD: "{{ .Values.mysql.auth.password }}"
  JWT_SECRET: "{{ .Values.member.env.JWT_SECRET }}"
  INTERNAL_API_KEY: "internal-key-change-in-prod"
  {{- if .Values.rabbitmq.enabled }}
  RABBITMQ_PASSWORD: "{{ .Values.rabbitmq.auth.password }}"
  {{- end }}
